### PR TITLE
allow simple arrays in schema

### PR DESCRIPTION
**Pull request by chirag04**
Consider simple array like:

var input = { a: [1,2, 3] };

var schema = { a: [true] };

_.deepPick(input, schema) // { a : {} }

### CODE REVIEW

**Comment by chirag04** [comment]
@mohsen1 Can you take a look here?

**Comment by mohsen1** [comment]
LGTM

**Comment by mohsen1** [comment]
Published at `v0.0.8`

**Comment by chirag04** [comment]
thanks! :+1:

**Pull request merged**
